### ISSUE TITLE
Make a zenodo for citations

### ISSUE THREAD

**Issue by conchoecia** [aziele/fastapy#3]
Hello! I enjoy this fasta parser. It is very lightweight and has some nice features, like seamless integration with gzipped files. Would you consider publishing it on Zenodo so that it has a doi so that I can cite it in an upcoming paper? Thank you for considering!

**Comment by aziele** [comment]
Hello! I'm happy to hear that you're enjoying the fasta parser :) I just published the repository on Zenodo and added the DOI badge to `README.md`. Thank you again!

**Comment by conchoecia** [comment]
That is great! Thank you, and I will cite it in my upcoming publication.
